import type { NextPage } from 'next';
import Head from 'next/head';
import { View } from '../../components/commons';
import { IRootState } from '../../redux/rootReducer';
import { connect } from 'react-redux';

// import LandingNavbar from '../../components/LandingPage/LandingNavbar';

const Home: NextPage<Props> = () => {
  return (
    <View className="p-star-fall">
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <LandingNavbar /> */}
      <View className="p-star-fall__banner" flexGrow={1}>
        <View className="p-star-fall__wave" />
        <View className="p-star-fall__wave" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
      </View>
    </View>
  );
};

type Props = ReturnType<typeof mapStateToProps> & ReturnType<typeof mapDispatchToProps>;
const mapStateToProps = (state: IRootState) => ({
  isAuthenticated: state.auth.isAuthenticated,
});

const mapDispatchToProps = (_dispatch: (_arg0: { payload: any; type: string }) => any) => ({});

export default connect(mapStateToProps, mapDispatchToProps)(Home);
