import type { NextPage } from 'next';
import Head from 'next/head';
import { View } from '../../components/commons';
import { Fade, SlideshowRef } from 'react-slideshow-image';
import { IMAGES } from '../../app-config/images';
import { IRootState } from '../../redux/rootReducer';
import { connect } from 'react-redux';
import { useRouter } from 'next/router';
import { PATHS } from '../../app-config/paths';
import { useRef, useState } from 'react';
import LandingNavbar from '../../components/LandingPage/LandingNavbar';

const fadeImages: {
  urlKey: keyof typeof IMAGES;
  caption: string;
  description: string;
}[] = [
  {
    urlKey: 'banner1',
    caption: 'Lorem Ipsum',
    description: 'Vestibulum semper tortor suscipit velit molestie, in convallis justo porta.',
  },
  {
    urlKey: 'banner2',
    caption: 'Nam auctor',
    description:
      'Nunc quis volutpat dui. Sed pellentesque magna a nunc vulputate, ut condimentum turpis lobortis.',
  },
  {
    urlKey: 'banner3',
    caption: 'Aliquam eget',
    description: 'Curabitur odio libero, rutrum quis volutpat vel, tristique sit amet lacus.',
  },
  {
    urlKey: 'banner4',
    caption: 'Duis sed',
    description: 'Nunc malesuada aliquam quam, eu auctor mi fringilla non.',
  },
];

const Home: NextPage<Props> = ({ isAuthenticated }) => {
  const router = useRouter();
  const [currentSlide, setSlide] = useState<number>(0);
  const bannerRef = useRef<SlideshowRef>();
  const handleBannerClick = () => {
    if (isAuthenticated) return router.push(PATHS.shopping);
    return router.push(PATHS.signIn);
  };
  const handleChangeSlide = (_from: number, to: number) => setSlide(to);
  const handleGoSlide = (to: number) => () => {
    if (to !== currentSlide) return bannerRef.current?.goTo(to);
  };
  return (
    <View className="p-star-fall">
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingNavbar />
      <View className="p-star-fall__banner" flexGrow={1}>
        <View className="p-star-fall__wave" />
        <View className="p-star-fall__wave" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
        <View className="p-star-fall__star" />
      </View>
    </View>
  );
};

type Props = ReturnType<typeof mapStateToProps> & ReturnType<typeof mapDispatchToProps>;
const mapStateToProps = (state: IRootState) => ({
  isAuthenticated: state.auth.isAuthenticated,
});

const mapDispatchToProps = (dispatch: (arg0: { payload: any; type: string }) => any) => ({});

export default connect(mapStateToProps, mapDispatchToProps)(Home);
