import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { PATHS } from '../app-config/constants';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {/* <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.tsx</code>
        </p> */}
        <p className={styles.description}>
          Hello <code className={styles.code}>Mai Thi charming OCD</code> yeu dau
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href={PATHS.SIGN_IN} className={styles.card}>
            <h2>Sign In Page &rarr;</h2>
            <p>File base routing.</p>
          </a>
          <Link href={PATHS.SIGN_UP}>
            <a className={styles.card}>
              <h2>Sign Up Page &rarr;</h2>
              <p>Next Link</p>
              <p>Not Reload Whole Page</p>
            </a>
          </Link>
          <Link href={PATHS.FETCHING}>
            <a className={styles.card}>
              <h2>Fetching Page &rarr;</h2>
              <p>getInitialProps</p>
              <p>get data from dump API</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
