import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { PATHS } from '../app-config/constants';
import { Button, Grid, Text, View } from '../components/commons';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <View className="c-container">
          <h1>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <View isRow className="mb-16">
            <Button label="Test Button" className="mr-16" />
            <Button label="Test Button 2" variant="outline" />
          </View>
          <Grid.Wrap>
            <Grid.Item>
              <Text>Text 1</Text>
            </Grid.Item>
            <Grid.Item>
              <Text>Text 2</Text>
            </Grid.Item>
          </Grid.Wrap>
        </View>
        {/* <div>
          <a href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href={PATHS.SIGN_IN}>
            <h2>Sign In Page &rarr;</h2>
            <p>File base routing.</p>
          </a>
          <Link href={PATHS.SIGN_UP}>
            <a>
              <h2>Sign Up Page &rarr;</h2>
              <p>Next Link</p>
              <p>Not Reload Whole Page</p>
            </a>
          </Link>
          <Link href={PATHS.FETCHING}>
            <a>
              <h2>Fetching Page &rarr;</h2>
              <p>getInitialProps</p>
              <p>get data from dump API</p>
              <p>Server Side Rendering</p>
            </a>
          </Link>
          <Link href={PATHS.USERS}>
            <a>
              <h2>Users Page &rarr;</h2>
              <p>getStaticProps</p>
              <p>get data from dump API</p>
              <p>Static Site Generation</p>
            </a>
          </Link>
        </div> */}
      </main>

      {/* <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
};

export default Home;
