import type { NextPage } from 'next';
import Head from 'next/head';
import { IMAGES } from '../app-config/images';
import { Button, Grid, Text, View } from '../components/commons';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <View className="c-container">
        <h1>Welcome to Landing Page</h1>
      </View>
    </div>
  );
};

export default Home;
